config/routes.rb
Rails.application.routes.draw do

  resources :passwords, controller: "users/passwords", only: [:create, :new]
  resource :session, controller: "users/sessions", only: [:create]

  resources :users do
    resource :password, controller: "users/passwords", only: [:create, :edit, :update]
    member do
      get :setup
      patch :complete
    end
  end

  get "/sign_in" => "users/sessions#new", as: "sign_in"
  delete "/sign_out" => "users/sessions#destroy", as: "sign_out"
  #get "/sign_up" => "clearance/users#new", as: "sign_up"
  get '/authentication/step-two', to: 'user_mfa_session#new'
  post '/user_mfa_session', to: 'user_mfa_session#create'

  resources :imports
  resources :activity_coaches
  #resources :attendances
  resources :memberships
  # People
  resources :people
  resources :participants
  resources :mentors
  resources :coaches

  resources :peers

  # Organisations
  resources :organisations

  # Events
  resources :events do
    resources :attendances
  end
  resources :fieldworks
  resources :meetings
  resources :activities

  resources :documents do
    resources :uploads do
      get :download, on: :member
    end
  end
  resources :interviews
  resources :galleries
  resources  :outputs

  # Home page
  root 'home#index'
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :person
  belongs_to :organisation
  validates_presence_of :person, :organisation

  scope :by_organisation, ->(filter) { where(organisation_id: filter) }
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_membership, only: [:show, :edit, :update, :destroy]

  # GET /memberships
  # GET /memberships.json
  def index
    scope = params[:filter].blank? ? Membership.all : Membership.by_organisation(params[:filter])
    @memberships = smart_listing_create(:memberships, scope, partial: 'memberships/listing')
    @organisations = Organisation.order(:name)
  end

  # GET /memberships/1
  # GET /memberships/1.json
  def show
  end

  # GET /memberships/new
  def new
    @membership = Membership.new
  end

  # GET /memberships/1/edit
  def edit
  end

  # POST /memberships
  # POST /memberships.json
  def create
    @membership = Membership.new(membership_params)

    respond_to do |format|
      if @membership.save
        format.html { redirect_to @membership, notice: 'Membership was successfully created.' }
        format.json { render :show, status: :created, location: @membership }
      else
        format.html { render :new }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memberships/1
  # PATCH/PUT /memberships/1.json
  def update
    respond_to do |format|
      if @membership.update(membership_params)
        format.html { redirect_to @membership, notice: 'Membership was successfully updated.' }
        format.json { render :show, status: :ok, location: @membership }
      else
        format.html { render :edit }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1
  # DELETE /memberships/1.json
  def destroy
    @membership.destroy
    respond_to do |format|
      format.html { redirect_to memberships_url, notice: 'Membership was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_membership
      @membership = Membership.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def membership_params
      params.require(:membership).permit(:person_id, :organisation_id, :member_start, :member_end, :notes)
    end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_form.html.erb
<div class="row">
  <div class="col-sm-5 col-md-4">

    <%= simple_form_for(@membership) do |f| %>
      <%= f.error_notification %>

      <div class="form-inputs">
        <%= f.association :person, collection: Participant.all %>
        <%= f.association :organisation %>
        <%= f.input :member_start %>
        <%= f.input :member_end %>
        <%= f.input :notes %>
      </div>

      <div class="form-actions">
        <%= f.button :submit, class: 'btn-primary' %>
        <%= link_to 'Cancel', people_path, class: 'btn btn-default' %>
      </div>
    <% end %>

  </div>
</div>

app/views/memberships/_listing.html.erb
<%- unless smart_listing.empty? %>
  <table class="table">
    <thead>
      <tr>
        <th>Participant</th>
        <th>Organisation</th>
        <th>Member start</th>
        <th>Member end</th>
        <th>Notes</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% smart_listing.collection.each do |membership| %>
        <tr>
          <td><%= link_to membership.person, person_path(membership.person) %></td>
          <td><%= link_to membership.organisation, organisation_path(membership.organisation) %></td>
          <td><%= membership.member_start %></td>
          <td><%= membership.member_end %></td>
          <td><%= membership.notes %></td>
          <td><%= link_to 'Show', membership %></td>
          <td><%= link_to 'Edit', edit_membership_path(membership) %></td>
          <td><%= link_to 'Destroy', membership, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= smart_listing.paginate %>
  <%= smart_listing.pagination_per_page_links %>

<% else %>
  <p class="warning">No records found</p>
<% end %>

app/views/memberships/edit.html.erb
<h1>Editing Membership</h1>

<%= render 'form'  %>

app/views/memberships/index.html.erb
<div class="row memberships">
  <div class="col-sm-2">
    <h1>Memberships</h1>
  </div>
  <div class="col-sm-3 pull-right">
    <%= smart_listing_controls_for(:memberships) do %>
      <div class="filter input-append form-group">
        <%= select_tag :filter, options_from_collection_for_select(@organisations, :id, :name), class: 'form-control', prompt: '--- Select an organisation ---' %>
      </div>
    <% end %>
  </div>
  <div class="col-sm-2 pull-right">
    <%= link_to "New Membership", new_membership_path, class: "btn btn-primary" %>
  </div>
</div>

<%= smart_listing_render(:memberships) %>

<br>

app/views/memberships/index.js.erb
<%= smart_listing_update(:memberships) %>

app/views/memberships/new.html.erb
<h1>New Membership</h1>

<%= render 'form'  %>

app/views/memberships/show.html.erb
<p>
  <strong>Person:</strong>
  <%= @membership.person %>
</p>

<p>
  <strong>Organisation:</strong>
  <%= @membership.organisation %>
</p>

<p>
  <strong>Member start:</strong>
  <%= @membership.member_start %>
</p>

<p>
  <strong>Member end:</strong>
  <%= @membership.member_end %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @membership.notes %>
</p>

<%= link_to 'Edit', edit_membership_path(@membership) %> |
<%= link_to 'Back', memberships_path %>