config/routes.rb
Rails.application.routes.draw do

  resources :passwords, controller: "users/passwords", only: [:create, :new]
  resource :session, controller: "users/sessions", only: [:create]

  resources :users do
    resource :password, controller: "users/passwords", only: [:create, :edit, :update]
    member do
      get :setup
      patch :complete
    end
  end

  get "/sign_in" => "users/sessions#new", as: "sign_in"
  delete "/sign_out" => "users/sessions#destroy", as: "sign_out"
  #get "/sign_up" => "clearance/users#new", as: "sign_up"
  get '/authentication/step-two', to: 'user_mfa_session#new'
  post '/user_mfa_session', to: 'user_mfa_session#create'

  resources :imports
  resources :activity_coaches
  #resources :attendances
  resources :memberships
  # People
  resources :people
  resources :participants
  resources :mentors
  resources :coaches

  resources :peers

  # Organisations
  resources :organisations

  # Events
  resources :events do
    resources :attendances
  end
  resources :fieldworks
  resources :meetings
  resources :activities

  resources :documents do
    resources :uploads do
      get :download, on: :member
    end
  end
  resources :interviews
  resources :galleries
  resources  :outputs

  # Home page
  root 'home#index'
end

app/models/activity_coach.rb
class ActivityCoach < ApplicationRecord
  belongs_to :event
  belongs_to :coach, foreign_key: :person_id
  validates_presence_of :event, :coach
end

app/controllers/activity_coaches_controller.rb
class ActivityCoachesController < ApplicationController
  before_action :set_activity_coach, only: [:show, :edit, :update, :destroy]

  # GET /activity_coaches
  # GET /activity_coaches.json
  def index
    @activity_coaches = ActivityCoach.all
  end

  # GET /activity_coaches/1
  # GET /activity_coaches/1.json
  def show
  end

  # GET /activity_coaches/new
  def new
    if params[:event_id]
      @activity_coach = ActivityCoach.new(event_id: params[:event_id])
    elsif params[:person_id]
      @activity_coach = ActivityCoach.new(person_id: params[:person_id])
    else
      @activity_coach = ActivityCoach.new
    end
  end

  # GET /activity_coaches/1/edit
  def edit
  end

  # POST /activity_coaches
  # POST /activity_coaches.json
  def create
    @activity_coach = ActivityCoach.new(activity_coach_params)

    respond_to do |format|
      if @activity_coach.save
        format.html { redirect_to @activity_coach, notice: 'Activity coach was successfully created.' }
        format.json { render :show, status: :created, location: @activity_coach }
      else
        format.html { render :new }
        format.json { render json: @activity_coach.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activity_coaches/1
  # PATCH/PUT /activity_coaches/1.json
  def update
    respond_to do |format|
      if @activity_coach.update(activity_coach_params)
        format.html { redirect_to @activity_coach, notice: 'Activity coach was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity_coach }
      else
        format.html { render :edit }
        format.json { render json: @activity_coach.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activity_coaches/1
  # DELETE /activity_coaches/1.json
  def destroy
    @activity_coach.destroy
    respond_to do |format|
      format.html { redirect_to activity_coaches_url, notice: 'Activity coach was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity_coach
      @activity_coach = ActivityCoach.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_coach_params
      params.require(:activity_coach).permit(:event_id, :person_id)
    end
end

app/helpers/activity_coaches_helper.rb
module ActivityCoachesHelper
end

app/views/activity_coaches/_form.html.erb
<%= simple_form_for(@activity_coach) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :event %>
    <%= f.association :coach %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/activity_coaches/edit.html.erb
<h1>Editing Activity Coach</h1>

<%= render 'form', activity_coach: @activity_coach %>

<%= link_to 'Show', @activity_coach %> |
<%= link_to 'Back', activity_coaches_path %>

app/views/activity_coaches/index.html.erb
<h1>Activity Coaches</h1>

<%= link_to 'New Activity Coach', new_activity_coach_path, class: "btn btn-primary" %>

<table class="table">
  <thead>
    <tr>
      <th>Event</th>
      <th>Coach</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activity_coaches.each do |activity_coach| %>
      <tr>
        <td><%= link_to activity_coach.event, event_path(activity_coach.event) %></td>
        <td><%= link_to activity_coach.coach, coach_path(activity_coach.coach) %></td>
        <td><%= link_to 'Show', activity_coach %></td>
        <td><%= link_to 'Edit', edit_activity_coach_path(activity_coach) %></td>
        <td><%= link_to 'Destroy', activity_coach, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/activity_coaches/new.html.erb
<h1>New Activity Coach</h1>

<%= render 'form', activity_coach: @activity_coach %>

<%= link_to 'Back', activity_coaches_path %>

app/views/activity_coaches/show.html.erb
<h1>Activity Coach</h1>

<%= link_to 'Edit', edit_activity_coach_path(@activity_coach), class: "btn btn-primary" %>
<%= link_to 'Back', activity_coaches_path, class: "btn btn-secondary" %>

<p>
  <strong>Activity:</strong>
  <%= link_to @activity_coach.event, event_path(@activity_coach.event) %>
</p>

<p>
  <strong>Person:</strong>
  <%= link_to @activity_coach.coach, person_path(@activity_coach.coach) %>
</p>