config/routes.rb
Rails.application.routes.draw do

  resources :passwords, controller: "users/passwords", only: [:create, :new]
  resource :session, controller: "users/sessions", only: [:create]

  resources :users do
    resource :password, controller: "users/passwords", only: [:create, :edit, :update]
    member do
      get :setup
      patch :complete
    end
  end

  get "/sign_in" => "users/sessions#new", as: "sign_in"
  delete "/sign_out" => "users/sessions#destroy", as: "sign_out"
  #get "/sign_up" => "clearance/users#new", as: "sign_up"
  get '/authentication/step-two', to: 'user_mfa_session#new'
  post '/user_mfa_session', to: 'user_mfa_session#create'

  resources :imports
  resources :activity_coaches
  #resources :attendances
  resources :memberships
  # People
  resources :people
  resources :participants
  resources :mentors
  resources :coaches

  resources :peers

  # Organisations
  resources :organisations

  # Events
  resources :events do
    resources :attendances
  end
  resources :fieldworks
  resources :meetings
  resources :activities

  resources :documents do
    resources :uploads do
      get :download, on: :member
    end
  end
  resources :interviews
  resources :galleries
  resources  :outputs

  # Home page
  root 'home#index'
end

app/models/organisation.rb
class Organisation < ApplicationRecord

  has_many :memberships
  has_many :people, through: :memberships

  scope :like, ->(filter) { where("name ILIKE :search OR email ILIKE :search", search: "%#{filter}%") }

  validates :activity, length: { maximum: 255 }

  def address
    "#{address_1}, #{address_2}, #{city}, #{postcode}"
  end

  def to_s
    name
  end
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  before_action :set_organisation, only: [:show, :edit, :update, :destroy]

  # GET /organisations
  # GET /organisations.json
  def index
    scope = params[:filter].blank? ? Organisation.all : Organisation.like(params[:filter])
    @organisations = smart_listing_create(:organisations, scope, partial: 'organisations/listing', default_sort: {name: :asc})
  end

  # GET /organisations/1
  # GET /organisations/1.json
  def show
  end

  # GET /organisations/new
  def new
    @organisation = Organisation.new
  end

  # GET /organisations/1/edit
  def edit
  end

  # POST /organisations
  # POST /organisations.json
  def create
    @organisation = Organisation.new(organisation_params)

    respond_to do |format|
      if @organisation.save
        format.html { redirect_to @organisation, notice: 'Organisation was successfully created.' }
        format.json { render :show, status: :created, location: @organisation }
      else
        format.html { render :new }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organisations/1
  # PATCH/PUT /organisations/1.json
  def update
    respond_to do |format|
      if @organisation.update(organisation_params)
        format.html { redirect_to @organisation, notice: 'Organisation was successfully updated.' }
        format.json { render :show, status: :ok, location: @organisation }
      else
        format.html { render :edit }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organisations/1
  # DELETE /organisations/1.json
  def destroy
    @organisation.destroy
    respond_to do |format|
      format.html { redirect_to organisations_url, notice: 'Organisation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organisation
      @organisation = Organisation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organisation_params
      params.require(:organisation).permit(:name, :activity, :email, :tel, :address_1, :address_2, :city, :postcode, :notes)
    end
end

app/helpers/organisations_helper.rb
module OrganisationsHelper
end

app/views/organisations/_form.html.erb
<div class="row">
  <div class="col-sm-5 col-md-4">
    <%= simple_form_for(@organisation) do |f| %>

      <%= f.error_notification %>

      <div class="form-inputs">
        <%= f.input :name %>
        <%= f.input :activity %>
        <%= f.input :email %>
        <%= f.input :tel %>
        <%= f.input :address_1 %>
        <%= f.input :address_2 %>
        <%= f.input :city %>
        <%= f.input :postcode %>
        <%= f.input :notes, input_html: {rows: 10} %>
      </div>

      <div class="form-actions">
        <%= f.button :submit, class: 'btn-primary' %>
        <%= link_to 'Cancel', people_path, class: 'btn btn-default' %>
      </div>
    <% end %>
  </div>
</div>

app/views/organisations/_listing.html.erb
<%- unless smart_listing.empty? %>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Activity</th>
        <th>Email</th>
        <th>Tel</th>
        <th>Address</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% smart_listing.collection.each do |organisation| %>
        <tr>
          <td><%= link_to organisation.name, organisation %></td>
          <td><%= organisation.activity %></td>
          <td><%= organisation.email %></td>
          <td><%= organisation.tel %></td>
          <td><%= organisation.address %></td>
          <td><%= link_to 'Show', organisation %></td>
          <td><%= link_to 'Edit', edit_organisation_path(organisation) %></td>
          <td><%= link_to 'Destroy', organisation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= smart_listing.paginate %>
  <%= smart_listing.pagination_per_page_links %>

<% else %>
  <p class="warning">No records found</p>
<% end %>

app/views/organisations/edit.html.erb
<h1>Editing Organisation</h1>

<%= render 'form' %>

app/views/organisations/index.html.erb
<div class="row organisations">
  <div class="col-sm-2">
    <h1>Organisations</h1>
  </div>
  <div class="col-sm-3 pull-right">
    <%= smart_listing_controls_for(:organisations) do %>
      <div class="filter input-append form-group">
        <%= text_field_tag :filter, '', class: "search form-control", placeholder: "Search by name or email", autocomplete: "off" %>
      </div>
    <% end %>
  </div>
  <div class="col-sm-2 pull-right">
    <%= link_to "New Organisation", new_organisation_path, class: "btn btn-primary" %>
  </div>
</div>

<%= smart_listing_render(:organisations) %>

<br>

app/views/organisations/index.js.erb
<%= smart_listing_update(:organisations) %>

app/views/organisations/new.html.erb
<h1>New Organisation</h1>

<%= render 'form' %>

app/views/organisations/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @organisation.name %></h1>

<p>
  <%= link_to 'Edit', edit_organisation_path(@organisation), class: "btn btn-primary" %>
  <%= link_to 'Back', organisations_path, class: "btn btn-secondary" %>
</p>

<p>
  <strong>Activity:</strong>
  <%= @organisation.activity %>
</p>

<p>
  <strong>Email:</strong>
  <%= @organisation.email %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @organisation.tel %>
</p>

<p>
  <strong>Address 1:</strong>
  <%= @organisation.address_1 %>
</p>

<p>
  <strong>Address 2:</strong>
  <%= @organisation.address_2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @organisation.city %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @organisation.postcode %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @organisation.notes %>
</p>

<h2>Members</h2>
<ul>
  <% @organisation.people.each do |member| %>
    <li><%= link_to member, participant_path(member) %></li>
  <% end %>
</ul>