config/routes.rb
Rails.application.routes.draw do

  resources :passwords, controller: "users/passwords", only: [:create, :new]
  resource :session, controller: "users/sessions", only: [:create]

  resources :users do
    resource :password, controller: "users/passwords", only: [:create, :edit, :update]
    member do
      get :setup
      patch :complete
    end
  end

  get "/sign_in" => "users/sessions#new", as: "sign_in"
  delete "/sign_out" => "users/sessions#destroy", as: "sign_out"
  #get "/sign_up" => "clearance/users#new", as: "sign_up"
  get '/authentication/step-two', to: 'user_mfa_session#new'
  post '/user_mfa_session', to: 'user_mfa_session#create'

  resources :imports
  resources :activity_coaches
  #resources :attendances
  resources :memberships
  # People
  resources :people
  resources :participants
  resources :mentors
  resources :coaches

  resources :peers

  # Organisations
  resources :organisations

  # Events
  resources :events do
    resources :attendances
  end
  resources :fieldworks
  resources :meetings
  resources :activities

  resources :documents do
    resources :uploads do
      get :download, on: :member
    end
  end
  resources :interviews
  resources :galleries
  resources  :outputs

  # Home page
  root 'home#index'
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :attendances
  has_many :people, through: :attendances

  # Only for coaches right now but putting it here just in case
  has_many :activity_coaches
  has_many :coaches, through: :activity_coaches

  validates :type, presence: true

  scope :like, ->(filter) { where("name ILIKE :search OR location ILIKE :search", search: "%#{filter}%") }

  def self.types
    ['Activity', 'Fieldwork', 'Meeting']
  end

  def duration
    event_end ? ((event_end - event_start) / 60 / 60).round(1) : 0
  end

  def to_s
    name
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = smart_listing_create(:events, scope, partial: 'events/listing', default_sort: {name: :asc})
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    def scope
      params[:filter].blank? ? Event.all : Event.like(params[:filter])
    end

    def trusted_parameters
      [:name, :event_start, :event_end, :event_type, :location, :notes, :other_attendees, :type]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(*trusted_parameters)
    end
end

app/helpers/events_helper.rb
module EventsHelper
  def path_for_new_event
    controller_class = controller_name.classify

    if Event.types.include?(controller_class)
      new_event_path(type: controller_class)
    else
      new_event_path
    end
  end
end

app/views/events/_form.html.erb
<div class="row">
  <div class="col-sm-12 col-md-5">
    <%= simple_form_for(@event) do |f| %>
      <%= f.error_notification %>

      <div class="form-inputs">
        <%= f.input :name %>
        <%= f.input :event_start, as: :datetime %>
        <%= f.input :event_end, as: :datetime %>
        <%- if @event.new_record? %>
          <%= f.input :type, collection: Event.types, prompt: 'Select a type', selected: params[:type] || @event.type %>
        <% end %>
        <%= f.input :event_type %>
        <%= f.input :location %>
        <%= f.input :notes, input_html: {rows: 10} %>
        <%= f.input :other_attendees, as: :text %>
      </div>

      <div class="form-actions">
        <%= f.button :submit, class: 'btn-primary' %>
        <%= link_to 'Cancel', events_path, class: 'btn btn-default' %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/_listing.html.erb
<%- unless smart_listing.empty? %>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Type</th>
        <th>Event start</th>
        <th>Event duration</th>
        <th>Event type</th>
        <th>Location</th>
        <th colspan="4"></th>
      </tr>
    </thead>

    <tbody>
      <% smart_listing.collection.each do |event| %>
        <tr>
          <td><%= link_to event.name, event_path(event) %></td>
          <td><%= event.type %></td>
          <td><%= event.event_start.to_date %></td>
          <td><%= event.duration %> hours</td>
          <td><%= event.event_type %></td>
          <td><%= event.location %></td>
          <td><%= link_to 'Manage Attendees', event_attendances_path(event)%></td>
          <td>
            <%= link_to event do %>
              <i class="glyphicon glyphicon-share-alt"></i>
            <% end %>
            <%= link_to edit_event_path(event) do %>
              <i class="glyphicon glyphicon-pencil"></i>
            <% end %>
            <%= link_to event, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <i class="glyphicon glyphicon-trash"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= smart_listing.paginate %>
  <%= smart_listing.pagination_per_page_links %>
<% else %>
  <p class="warning">No records found</p>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event: <%= @event.to_s%></h1>

<%= render 'form' %>

app/views/events/index.html.erb
<div class="row events">
  <div class="col-sm-2">
    <h1><%= t("#{controller_name}.page_title") %></h1>
  </div>
  <div class="col-sm-3 pull-right">
    <%= smart_listing_controls_for(:events) do %>
      <div class="filter input-append form-group">
        <%= text_field_tag :filter, '', class: "search form-control", placeholder: "Search by name or location", autocomplete: "off" %>
      </div>
    <% end %>
  </div>
  <div class="col-sm-2 pull-right">
    <%= link_to t("#{controller_name}.new_button"), path_for_new_event, class: "btn btn-primary" %>
  </div>
</div>

<%= smart_listing_render(:events) %>

<br>

app/views/events/index.js.erb
<%= smart_listing_update(:events) %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

app/views/events/show.html.erb
<h1><%= @event.name %> <small><%= @event.type %></small></h1>

<p>
  <%= link_to 'Edit', edit_event_path(@event), class: "btn btn-primary" %>
  <%= link_to 'Manage Attendees', event_attendances_path(@event), class: "btn btn-primary" %>
  <%= link_to 'Back', events_path, class: "btn btn-secondary" %>
</p>

<p>
  <%= @event.event_start %> - <%= @event.event_end %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<p>
  <strong>Other attendees :</strong>
  <%= @event.other_attendees %>
</p>

<h2>Notes</h2>
<p>
  <%= @event.notes %>
</p>

<% if @event.type == "Activity" %>
  <h2>Coaches</h2>
  <% if @event.coaches.length > 0 %>
    <ul>
      <% @event.coaches.each do |coach| %>
        <li><%= link_to coach, coach_path(coach) %></li>
      <% end %>
    </ul>
  <% else %>
    <p>No coaches listed! Add one?</p>
  <% end %>
  <p>
    <%= link_to "Add a coach", new_activity_coach_path({event_id: @event.id}) %>
  </p>
<% end %>